### ISSUE TITLE
inputs missing

### ISSUE THREAD

**Issue by Ad4m69** [OriSpirit/SpellMacro#1]
when using the same type of click multiple time in a row it misses Most of them at the speed of 50ms, and misses Some of the clicks at the speed of 100ms. for example RRR cast as R or RR

**Comment by RainVaporeon** [comment]
Sorry for getting back to you late, however that's not something I can solve (Not sure why, maybe lag?)

The casting method is the same as Wynntils, you might want to tune the delay higher if you are encountering missing inputs.
